### ISSUE TITLE
Umbrella / Meta: Browser Permissions for WebDriver BiDi as an extension module

### ISSUE THREAD

**Issue by thiagowfx** [w3c/permissions#424]
WebDriver BiDi spec umbrella issue: https://github.com/w3c/webdriver-bidi/issues/587

"Interacting with Permissions for Powerful Features"

The [**WebDriver BiDi spec**](https://w3c.github.io/webdriver-bidi/) should support interaction with **browser permissions** as an [extension module](https://w3c.github.io/webdriver-bidi/#extension-modules). These permissions represent a user's choice to allow or deny access to "powerful features" of the platform. For developers, the specification standardizes an API to query the permission state of a powerful feature, and be notified if a permission to use a powerful feature changes state.

The Permissions spec already supports [WebDriver classic](https://www.w3.org/TR/permissions/#set-permission-command). This bug is about making it support [WebDriver BiDi](https://w3c.github.io/webdriver-bidi/) as well.

[For Puppeteer it would be nice to add as the next step](https://github.com/w3c/permissions/pull/425#pullrequestreview-1734377396):

# Tracking

- [ ] MPV / Initial PR: https://github.com/w3c/permissions/pull/425
- [ ] TODO: Add `user context` to `SetPermissionParameters`
- [ ] TODO: Add `origin` to `SetPermissionParameters`

**Comment by thiagowfx** [comment]
cc @OrKoN @mathiasbynens
